<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("User Help");
$this->breadcrumbs=array(
	UserModule::t("Help"),
);?><h2><?php echo UserModule::t('User Help'); ?></h2>
<h3>API Key Status</h3>
<p>The only modification that you can do to an API key is to <i class='icon-trash'></i> delete it. This is by design, as <strong><?php echo Yii::app()->name ?></strong> allows you to fine tune access at the character level. When deleting a key, <strong><?php echo Yii::app()->name ?></strong> will notify you of any changes that may result to registered characters as a consequence of key deletion and you will have the option to confirm or cancel the request. <span class="label label-important">Warning</span> While deleting a key, it will also delete any registered characters which solely rely on the key for data. Character deletion will irrecoverably delete all data associated with character.</p>
<p>There are a few scenario's when you must refresh the key - usually when you change parameters of the key on the EVE Online API Support website (such as changing the vCode, access mask, expiration, etc). The state of your key is expressed via handy status icons:</p>
<ul>
	<li><i class='icon-ok'></i> <strong>Active</strong>: No issues here, working as intended.</li>
	<li><span style='background-color: #FCF8E3'><i class='icon-warning-sign'></i> <strong>Warning</strong></span>: With this icon and background color, your key is working but it is not optimal. This usually means that the key's access mask was changed on the EVE server side and needs to be updated to properly reflect. Please click the <i class='icon-refresh'></i> refresh button to refresh the key; failing to do so may lead to unintended API Access conflicts.</li>
	<li><span style='color:black;' class='alert-error'><i class='icon-warning-sign'></i> <strong>Disabled</strong></span>: <strong><?php echo Yii::app()->name ?></strong> has disabled this key. The reasons vary, but can include expired/deleted keys or a change to the vCode, or another change that may similarly prevent authorization. Please take a look at the EVE Online  API Support website and correct any errors. After they have been corrected, please click the <i class='icon-refresh'></i> refresh button to refresh the key; failing to do so may lead to unintended API Access conflicts.</li>
</ul>

<h3>Character Actions</h3>
<p>Characters have a set of icons in their display that commit various actions. The following is an explanation of each:</p>
<ul>
	<li><i class='icon-ok'></i> <strong>Activate</strong>: Activates character. API calls will start downloading character data at next tick. Default access mask is a combination of all registered API keys that character is associated with.</li>
	<li><i class='icon-plus'></i> <strong>Enable</strong>: Enables the downloading of API data associated with that character.</li>
	<li><i class='icon-minus'></i> <strong>Disable</strong>: Disables the downloading of any API data associated with that character. <i>Note:</i> Disabling a character will disable new data from being fetched and accessed via <strong><?php echo Yii::app()->name ?></strong> applications, but will not delete existing data in database. See <i class='icon-trash'></i> Delete)</li>
	<li><i class='icon-user'></i> <strong>Default</strong>: Character will become user's default character for <strong><?php echo Yii::app()->name ?></strong> applications. Current session character can always be changed in the user menu.</li>
	<li><i class='icon-trash'></i> <strong>Delete</strong>: Deletes the character from the database along with <i>all</i> data. <span class="label label-important">Warning</span> This cannot be reversed, however you can always activate the character again. Legacy data (for example, transactions over 30 days) will not be able to be fetched.</li>
</ul>

<h3>Why do I get an error when activating my character?</h3>
<p><strong><?php echo Yii::app()->name ?></strong> is designed around Yapeal, an EVE API library that is a bit different than other libraries in that it stores API data into a database and polls for it at regular intervals. One of the database tables used stores which characters are 'activated' and thus which characters get their data pulled from API servers. The issue stems from the fact that this table can only take unique characters (ie: no duplicates).</p>
<p>To make a long story short, the reason that you cannot activate your character is simply because it's already been activated in the database. This may cause confusion, as you may ask yourself "if it's activated then why doesn't it show it on my settings page". The reason for that is also simple: Someone else may be using your API key and already activated your character.</p>
<p>This may be a simple oversight of your corp leadership using your key in <strong><?php echo Yii::app()->name ?></strong> to get your skills and other info for recruitment, or it may be a third party that has access to an API key with the character in question. For this reason, in the case of this error, we display all the keyIDs that we have in our database associated with this character. If you are the true owner of the character, you can simply log into the official EVE Online API Support website and disable, delete, or otherwise change the authentication of the offending keys. This will deactivate the key from our system, and open up the character for activation once more.</p>