<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("User Help");
$this->breadcrumbs=array(
	UserModule::t("Help"),
);?><h2><?php echo UserModule::t('User Help'); ?></h2>
<h3>What exactly do the actions do?</h3>
<p>API keys and characters have a set of icons in their display that commit various actions. The following is an explaination:</p>
<ul>
	<li><i class='icon-plus'></i> <strong>Enable <small>(API AND CHARACTER)</small></strong>: For API keys, this allows that key to be used in API pulls for the characters/corporation the key represents. For characters, enables the downloading of API data associated with that character.</li>
	<li><i class='icon-minus'></i> <strong>Disable <small>(API AND CHARACTER)</small></strong>: For API keys, this disables the key for use in API calls for the characters/corporation the key represents. For characters, disables the downloading of any API data associated with that character. <strong>Eg:</strong> You have two keys for a character: one the provides character sheet data, and one that provides account balance. If you disable the key that allows character sheet access, only the account balance will be updated in future API calls. <i>Note:</i> Disabling a character will disable new data from being fetched and accessed via <strong><?php echo Yii::app()->name ?></strong> applications, but will not delete existing data in database. See `Delete`)</li>
	<li><i class='icon-trash'></i> <strong>Delete <small>(API AND CHARACTER)</small></strong>: For API keys, will delete the key from the database and, if registered characters rely on that key alone, will delete them as well. For characters, delete will delete the character from the database along with <i>all</i> data.</li>
	<li><i class='icon-ok'></i> <strong>Activate <small>(CHARACTER ONLY)</small></strong>: API calls will start downloading character data at next tick. Default access mask is a combination of all registered API keys that character is associated with.</li>
	<li><i class='icon-user'></i> <strong>Default <small>(CHARACTER ONLY)</small></strong>: Makes the current character the default character for <strong><?php echo Yii::app()->name ?></strong> applications. Current character can always be changed in the user menu.</li>
</ul>

<h3>Why do I get an error when activating my character?</h3>
<p><strong><?php echo Yii::app()->name ?></strong> is designed around Yapeal, an EVE API library that is a bit different than other libraries in that it stores API data into a database and polls for it at regular intervals. One of the database tables is used to store which characters are 'activated' and thus which characters get their data pulled from API servers. The issue stems from the fact that this table can only take unique characters (ie: no duplicates).</p>
<p>To make a long story short, the reason that you cannot activate your character is simply because it's already been activated in the database. You may ask yourself "well, if it's activiated then why doesn't it show it on my settings page". The reason for that is also simple: Someone else may be using your API key and already activated your character.</p>
<p>This may be a simple oversight of your corp leadership using your key in <strong><?php echo Yii::app()->name ?></strong> to get your skills and other info for recruitment, or it may be a third party that has access to an API key with the pertaining character. For this reason, in the case of this error, we display all the keyIDs that we have in our database associated with this character. If you are the true owner of the character, you can simply log into the official EVE Online API Support website and disable the offending keys. This will deactivate the key from our system, and open up the character for activation once more.</p>